### ISSUE TITLE
Intergalactic FM add on not working in Kodi 19

### ISSUE THREAD

**Issue by MathieuBordere** [intergalacticfm/plugin.audio.intergalacticfm#1]
Is apparently related to the move from python2 to python3.

**Comment by PanderMusubi** [comment]
Thanks. Yeah, we are working on this. Will communicate here when it is fixed. :musical_note:

**Comment by MathieuBordere** [comment]
Any news on this? I'll probably take a look at this myself.

**Comment by PanderMusubi** [comment]
Thanks for the PR. Good to get this working again on the latest Kodi. Will look at it next week.

**Comment by PanderMusubi** [comment]
Been working on both plugins a bit but need help. How can get them working, mainly Python 3 import issues. @MathieuBordere @sphaero @elkrojo

**Comment by PanderMusubi** [comment]
Fixed
